

services:
  db:
    image: mongo:5
    container_name: pokemonDB
    ports:
      - 27017:27017
    volumes:
      - pokemon_mongo_v:/data/db
    environment:
      MONGODB_DATABASE: nest-pokemon

volumes:
  pokemon_mongo_v:
    external: false